name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    name: "pups lint"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        ruby: ["3.3"]

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rubocop --force-exclusion pups.gemspec
  test:
    name: "pups tests"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        ruby: ["3.3"]

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run minitest
        run: |
          rake test

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Release Gem
        uses: discourse/publish-rubygems-action@v2
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          GIT_EMAIL: team@discourse.org
          GIT_NAME: discoursebot
