name: Tests

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    name: "pups tests"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        ruby: ["3.2"]

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run minitest
        run: |
          rake test
